### ISSUE TITLE
Change File Name

### ISSUE THREAD

**Issue by kwagyeman** [chrisbuerginrogers/LabVIEWOpenMV#1]
Please change the filename of the "_Simple Demo.vi" to "_Simple_Demo.vi". I can't have spaces in the file name when releasing for OpenMV IDE. The Make file build system breaks on this.

**Comment by chrisbuerginrogers** [comment]
done.
Note - they will have to delete the "_master" on the folder to make things work - any good workarounds for this?  I put it all in the README.md

**Comment by kwagyeman** [comment]
I can't actually run labview code. Just releasing the folder as is.

**Comment by chrisbuerginrogers** [comment]
Yeah - the _master is a GitHub addition - not LabVIEW.  Thanks -
